name: Trigger Deployment

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Infra Deployment
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.INFRA_DEPLOY_TOKEN }}" \
            https://api.github.com/repos/777anishsingh/DevConnectInfra/dispatches \
            -d '{"event_type":"backend-updated"}'